import { useState } from 'react';
import { createUserWithEmailAndPassword, signInWithEmailAndPassword } from 'firebase/auth';
import { doc, setDoc } from 'firebase/firestore';
import { auth, db } from '../firebase';

const Auth = () => {
  const [email, setEmail] = useState('');
    const [password, setPassword] = useState('');
      const [isLogin, setIsLogin] = useState(true);
        const [userType, setUserType] = useState('buyer');

          const handleSubmit = async (e) => {
              e.preventDefault();
                  try {
                        if (isLogin) {
                                await signInWithEmailAndPassword(auth, email, password);
                                        alert('Login successful!');
                                              } else {
                                                const userCredential = await createUserWithEmailAndPassword(auth, email, password);

                                                              // Save user type to Firestore
                                                              await setDoc(doc(db, 'users', userCredential.user.uid), {
                                                                email: email,
                                                                  userType: userType, // This saves farmer/buyer choice
                                                                    createdAt: new Date()
                                                                    });

                                                                    alert('Account created successfully!');
                                                                    }
                                                                        } catch (error) {
                                                                              alert(error.message);
                                                                                  }
                                                                                    };

                                                                                      return (
                                                                                          <div style={{ padding: '20px', maxWidth: '400px', margin: '0 auto' }}>
                                                                                                <h2 style={{ textAlign: 'center', color: 'green' }}>
                                                                                                        {isLogin ? 'Login to AgriMall' : 'Join AgriMall'}
                                                                                                              </h2>
                                                                                                                    
                                                                                                                          {!isLogin && (
                                                                                                                                  <div style={{ marginBottom: '15px' }}>
                                                                                                                                            <label>I am a:</label>
                                                                                                                                                      <div style={{ display: 'flex', gap: '10px', marginTop: '5px' }}>
                                                                                                                                                                  <button
                                                                                                                                                                                type="button"
                                                                                                                                                                                              onClick={() => setUserType('farmer')}
                                                                                                                                                                                                            style={{ 
                                                                                                                                                                                                                            flex: 1, 
                                                                                                                                                                                                                                            padding: '8px', 
                                                                                                                                                                                                                                                            backgroundColor: userType === 'farmer' ? 'green' : '#ccc',
                                                                                                                                                                                                                                                                            color: 'white',
                                                                                                                                                                                                                                                                                            border: 'none',
                                                                                                                                                                                                                                                                                                            borderRadius: '5px'
                                                                                                                                                                                                                                                                                                                          }}
                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                    Farmer
                                                                                                                                                                                                                                                                                                                                                                </button>
                                                                                                                                                                                                                                                                                                                                                                            <button
                                                                                                                                                                                                                                                                                                                                                                                          type="button"
                                                                                                                                                                                                                                                                                                                                                                                                        onClick={() => setUserType('buyer')}
                                                                                                                                                                                                                                                                                                                                                                                                                      style={{ 
                                                                                                                                                                                                                                                                                                                                                                                                                                      flex: 1, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                      padding: '8px', 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      backgroundColor: userType === 'buyer' ? 'green' : '#ccc',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      color: 'white',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      border: 'none',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      borderRadius: '5px'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Buyer
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <form onSubmit={handleSubmit} style={{ display: 'flex', flexDirection: 'column', gap: '15px' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <label>Email</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                type="email"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            value={email}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onChange={(e) => setEmail(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    style={{ width: '100%', padding: '10px', marginTop: '5px' }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                required
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <label>Password</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  type="password"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              value={password}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onChange={(e) => setPassword(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      style={{ width: '100%', padding: '10px', marginTop: '5px' }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  required
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      type="submit"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                style={{ 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            padding: '12px', 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        backgroundColor: 'green', 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    color: 'white', 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                border: 'none', 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            borderRadius: '5px' 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {isLogin ? 'Login' : 'Sign Up'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </form>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p style={{ textAlign: 'center', marginTop: '15px' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {isLogin ? "Don't have an account? " : "Already have an account? "}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      onClick={() => setIsLogin(!isLogin)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                style={{ color: 'green', background: 'none', border: 'none', textDecoration: 'underline' }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {isLogin ? 'Sign Up' : 'Login'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      export default Auth;