import { useState, useEffect } from 'react';
import { auth, db } from './firebase';
import { onAuthStateChanged, signOut } from 'firebase/auth';
import { doc, getDoc } from 'firebase/firestore';
import LandingPage from './components/LandingPage';
import FarmerDashboard from './components/FarmerDashboard';
import BuyerDashboard from './components/BuyerDashboard';
import './App.css';

function App() {
  const [user, setUser] = useState(null);
    const [userType, setUserType] = useState(null);
      const [loading, setLoading] = useState(true);

        // Get user type from Firestore
          const getUserType = async (currentUser) => {
              try {
                    const userDoc = await getDoc(doc(db, 'users', currentUser.uid));
                          if (userDoc.exists()) {
                                  setUserType(userDoc.data().userType);
                                        } else {
                                                setUserType('buyer'); // Default fallback
                                                      }
                                                          } catch (error) {
                                                                console.error('Error getting user type:', error);
                                                                      setUserType('buyer'); // Fallback
                                                                          }
                                                                              setLoading(false);
                                                                                };

                                                                                  useEffect(() => {
                                                                                      const unsubscribe = onAuthStateChanged(auth, (currentUser) => {
                                                                                            setUser(currentUser);
                                                                                                  if (currentUser) {
                                                                                                          getUserType(currentUser);
                                                                                                                } else {
                                                                                                                        setUserType(null);
                                                                                                                                setLoading(false);
                                                                                                                                      }
                                                                                                                                          });
                                                                                                                                              return () => unsubscribe();
                                                                                                                                                }, []);

                                                                                                                                                  const handleLogout = async () => {
                                                                                                                                                      try {
                                                                                                                                                            await signOut(auth);
                                                                                                                                                                } catch (error) {
                                                                                                                                                                      console.error('Logout error:', error);
                                                                                                                                                                          }
                                                                                                                                                                            };

                                                                                                                                                                           if (loading) {
                                                                                                                                                                                    return (
                                                                                                                                                                                          <div style={{ 
                                                                                                                                                                                                  display: 'flex', 
                                                                                                                                                                                                          justifyContent: 'center', 
                                                                                                                                                                                                                  alignItems: 'center', 
                                                                                                                                                                                                                          height: '100vh',
                                                                                                                                                                                                                                  backgroundColor: '#f0f9f0'
                                                                                                                                                                                                                                        }}>
                                                                                                                                                                                                                                                <div style={{ textAlign: 'center' }}>
                                                                                                                                                                                                                                                          <h2 style={{ color: 'green' }}>🌱 AgriMall</h2>
                                                                                                                                                                                                                                                                    <p>Loading...</p>
                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                          if (!user) {
                                                                                                                                                                                                                                                                                              return <LandingPage />;
                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                  return (
                                                                                                                                                                                                                                                                                                      <div style={{ padding: '20px', minHeight: '100vh', backgroundColor: '#f0f9f0' }}>
                                                                                                                                                                                                                                                                                                            <div style={{ maxWidth: '1200px', margin: '0 auto' }}>
                                                                                                                                                                                                                                                                                                                    <header style={{ 
                                                                                                                                                                                                                                                                                                                              backgroundColor: 'white', 
                                                                                                                                                                                                                                                                                                                                        padding: '15px', 
                                                                                                                                                                                                                                                                                                                                                  borderRadius: '10px', 
                                                                                                                                                                                                                                                                                                                                                            marginBottom: '20px',
                                                                                                                                                                                                                                                                                                                                                                      boxShadow: '0 2px 4px rgba(0,0,0,0.1)'
                                                                                                                                                                                                                                                                                                                                                                              }}>
                                                                                                                                                                                                                                                                                                                                                                                        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                                                                                                                                                                                                                                                                                                                                                                                                    <h1 style={{ color: 'green', margin: 0 }}>🌱 AgriMall</h1>
                                                                                                                                                                                                                                                                                                                                                                                                                <div style={{ display: 'flex', alignItems: 'center', gap: '15px' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                              <span style={{ color: '#666' }}>Welcome, {user.email}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                            <span style={{ 
                                                                                                                                                                                                                                                                                                                                                                                                                                                            padding: '4px 8px', 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            backgroundColor: userType === 'farmer' ? '#10b981' : '#3b82f6',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            color: 'white',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            borderRadius: '12px',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            fontSize: '12px'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {userType === 'farmer' ? '👨‍🌾 Farmer' : '🛒 Buyer'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      onClick={handleLogout}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        backgroundColor: '#ef4444',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          color: 'white',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            padding: '8px 16px',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              border: 'none',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                borderRadius: '5px'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Logout
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </header>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {userType === 'farmer' ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <FarmerDashboard />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <BuyerDashboard />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            export default App;
